[[questions]]
type = "ShortAnswer"
prompt.prompt = "What is the struct for a rectangle called in Macroquad?"
answer.answer = "Rect"
context = "The Macroquad `math` namespace contains representations for many different mathematical concepts."
id = "dc4c5484-fee2-48eb-bd29-581517c92c36"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
What is the name of the method of `Rect` that checks if it partly covers another rectangle?
"""
prompt.distractors = [
    "`contains()`",
    "`intersect()`",
    "`combine_with()`"
]
answer.answer = "`overlaps()`"
context = """
The method `overlaps()` checks if two rectangles are overlapping.
"""
id = "64e016dc-2d80-426e-b37d-30fbc97f0ef5"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which function checks if a key was pressed during the current frame?
"""
prompt.distractors = [
    "`is_key_down()`",
    "`is_key_released()`",
    "`get_char_pressed()`"
]
answer.answer = "`is_key_pressed()`"
context = """
The function `is_key_pressed()` is only true during the first frame the key was pressed
while `is_key_down()` continues to be true for every frame the key is being pressed.
"""
id = "a218ea1c-7fe4-42fb-934f-eba4582274d6"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Which function is used to display text on the screen with additional parameters?"
answer.answer = "draw_text_ex"
context = """
Some functions in Macroquad has a corresponding function with the suffix `_ex` which
takes an argument with a parameter struct.
"""
id = "3377c9db-63d4-42de-9bab-5405eb1e93d3"

