[[questions]]
type = "ShortAnswer"
prompt.prompt = """
"""
answer.answer = "load_texture"
context = """
"""
id = "b640049a-7e02-425d-afb2-a66927bfa513"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
"""
prompt.distractors = [
    "",
    "",
    ""
]
answer.answer = ""
context = """
"""
id = "8e1986c3-b4f7-436f-a491-d7af9a4c532d"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
"""
prompt.distractors = [
    "",
    "",
    ""
]
answer.answer = ""
context = """

"""
id = "3a229219-55bb-47e7-b1c9-6ce01462eb53"
