[[questions]]
type = "ShortAnswer"
prompt.prompt = "What is the name of graphics library Macroquad uses?"
answer.answer = "miniquad"
context = "Miniquad is a small graphics library while Macroquad is a game library."
id = "8754972b-e6e4-46b2-adbf-e261b673d1d3"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
What is the function `rand::gen_range()` used for?
"""
prompt.distractors = [
    "It returns a list of numbers between the first and second argument.",
    "It displays a line on the screen between the coordinates used as argument.",
    "It returns a random number between 0 and 1.",
    "It returns a random number between 0 and `u32::MAX`."
]
answer.answer = "It returns a random number between the two arguments."
context = """
The function `rand::gen_range()` takes the argument `low` and `high`
and returns a number of the same type.
"""
id = "61544d0e-b4b9-449f-b3cf-498c54d0bd8f"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
What happens when using the function `rand::srand(42)`?
"""
prompt.distractors = [
    "The function `rand()` will always return the number 42.",
    "It's a compilation error since the argument isn't a time type.",
    "It returns a random number between `0` and `42`."
]
answer.answer = "The values returned by `rand()` will be the same every time the program is run."
context = """
The pseudo number generator needs to be seeded with different values every time the application is run
in order for the `rand()`function to return random values.
"""
id = "c5cb1795-1f08-48bb-8bd2-64f70fc8118d"
