[[questions]]
type = "ShortAnswer"
prompt.prompt = "What is the attribute macro called that is used to annotate the Macroquad main function?"
answer.answer = "macroquad::main"
context = "It can be used like this: `#[macroquad::main(\"My game\")]`"
id = "de532a4a-7d2c-4a72-94c1-529df8d5a626"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Vad händer om `macroquad::main`-attributet får argumentet "RED"?
What happens if the `macroquad::main` attribute has the argument "RED"?
"""
prompt.distractors = [
    "The window background will be red.",
    "Nothing, it is just a comment."
]
answer.answer = "The window title will be \"RED\"."
context = """
If the argument is a string it will be used as the window title.
"""
id = "e0a941ab-119a-4c33-8394-f64f7b25f32d"

[[questions]]
type = "Tracing"
prompt.program = """
use macroquad::prelude::*;
#[macroquad::main("Macroquad")]
fn main() {
    loop {
        next_frame().await
    }
}
"""
answer.doesCompile = false
answer.lineNumber = 3
context = """
It won't compile since the `main` function isn't marked as `async`.
"""
id = "fb80a3a0-be24-4111-b05f-fda4d347acb4"
