[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which enum variant represents the Escape key?
"""
prompt.distractors = [
  "`KeyCode::Esc`",
  "`Key::Escape`",
  "`Code::Esc`"
]
answer.answer = "`KeyCode::Escape`"
context = """
The most variant for keys in the `KeyCode` enums aren't abbreviated.
"""
id = "589fe1df-eac3-4fc5-9b7a-21cc60b838db"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
How can a Macroquad application be exited?
"""
prompt.distractors = [
  "`macroquad::exit()`",
  "`miniquad::quit()`",
  "`quit_program()`"
]
answer.answer = "`std::process::exit(0)`"
context = """
There is no special way to exit a program in Macroquad.
But it's possible to use the normal Rust ways of exiting a program.
"""
id = "13771a47-2f7a-4f26-970f-e24b3b6f8755"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which argument order of the `measure_text()` function is correct?
"""
prompt.distractors = [
    "`measure_text(text, font_size, font_scale, font)`",
    "`measure_text(text, font_size, font, font_scale)`",
    "`measure_text(text, font_scale, font, font_size)`",
    "`measure_text(font, font_size, font_scale, text)`"
]
answer.answer = "`measure_text(text, font, font_size, font_scale)`"
context = """
The first argument is `text`, just as in the `draw_text()` function.
"""
id = "08aad258-1e50-4542-b5e2-c3fcfb7e286f"
