[[questions]]
type = "ShortAnswer"
prompt.prompt = "What is the function called that returns the window height?"
answer.answer = "screen_height"
context = "It can be used like this: `let height = screen_height()`"
id = "d9305baf-c759-4daa-8299-c58af3004825"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
How do you check if the space bar is currently being pressed?
"""
prompt.distractors = [
  "`is_key_down(Key::Space)`",
  "`is_space_down()`",
  "`is_key_pressed(SPACE)`",
  "`is_key_released(KeyCode::Space)`"
]
answer.answer = "`is_key_down(KeyCode::Space)`"
context = """
The function `is_key_down()` takes the enum `KeyCode` as argument and returns true if that key is being pressed.
"""
id = "aae4f36e-7ce4-499c-b0f1-5b2e838dba2b"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which of the following alternatives of the function `draw_circle()` has the correct argument order?
"""
prompt.distractors = [
    "`draw_circle(color, x, y, radius)`",
    "`draw_circle(radius, x, y, color)`",
    "`draw_circle(radius, color, x, y)`",
    "`draw_circle(color, radius, x, y)`",
    "`draw_circle(x, y, color, radius)`"
]
answer.answer = "`draw_circle(x, y, radius, color)`"
context = """
The Macroquad draw functions ususally start with coordinates and end with the color to use.
"""
id = "add860db-3099-471f-92eb-85ac7a9fa821"

