[[questions]]
type = "ShortAnswer"
prompt.prompt = """
What is the name of the crate for the Macroquad particle system?
"""
answer.answer = "macroquad-particles"
context = """
The Macroquad particle system isn't included by default but has to be
added to the `Cargo.toml` file to be used.
"""
id = "6488829a-94fb-493d-a835-95dad5cdef9a"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which struct is used to set particle system parameters?
"""
prompt.distractors = [
  "`EmitterParams`",
  "`ParticleConfig`",
  "`ParticleParams`",
  "`particles::Config`",
  "`particles::Params`"
]
answer.answer = "`EmitterConfig`"
context = """
The `EmitterConfig` struct has many fields to configure the emitter,
such as the look, size, speed and lots of other things.
"""
id = "fe83c08f-c2e3-4026-86be-0931c7524e64"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
How do you draw a partcle explosion in the variable `particle`?
"""
prompt.distractors = [
    "`draw_particle(particle, *coords)`",
    "`particle.emit(*coords)`",
    "`emit_particle(particle, *coords)`"
]
answer.answer = "`particle.draw(*coords)`"
context = """
The structen
[`Emitter`](https://docs.rs/macroquad-particles/latest/macroquad_particles/struct.Emitter.html)
has the method `draw()` which takes a coordinate where the particles are being emitted from.
"""
id = "6a16b9a6-cc60-4c52-8c8d-8e6950b388d2"
