[[questions]]
type = "ShortAnswer"
prompt.prompt = "Which function is used to measure the text dimensions?"
answer.answer = "measure_text"
context = "The function `measure_text` returns a `TextDimensions` struct."
id = "c9ee860f-c229-46f9-986e-3f9ebd33e4fa"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which field is **NOT** included in the struct `TextDimensions`?
"""
prompt.distractors = [
  "`width`",
  "`height`",
  "`offset_y`"
]
answer.answer = "`offset_x`"
context = """
The field `offset_y` contains the distance from the base line of the text.
"""
id = "12d7dee6-0a6c-43a3-8a90-7900fa6eb1dd"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which function is used to read a file and return it as a string?
"""
prompt.distractors = [
    "`load_file()`",
    "`load_text()`",
    "`read_file_as_string()`"
]
answer.answer = "`load_string()`"
context = """
The `load_string()` function reads a file using `load_file()` and returns it as a `String`.
"""
id = "7ada75f0-2509-46d7-b785-150d01cdaef6"
