[[questions]]
type = "ShortAnswer"
prompt.prompt = """
Which function is used to load textures in Macroquad?
"""
answer.answer = "load_texture"
context = """
Use `load_texture()` to load a PNG image and store it in GPU memory.
"""
id = "a31046aa-56e4-4416-8a49-874ea3000e25"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
What is the filter mode `FilterMode::Nearest` used for on a texture?
"""
prompt.distractors = [
    "It's used to scale the texture linearly.",
    "It's used to filter out the nearest pixels.",
    "It's used to filter out pixels that are close to each other.",
]
answer.answer = "It's used to ensure that pixelated graphics is scaled to the nearest pixel."
context = """
The filter mode `FilterMode::Nearest` is generally used for pixel graphics
while `FilterMode::Linear` is used for high resolution textures.
"""
id = "90372ead-ab70-4d1a-b93b-cb5c1e600eef"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Why should you use the function `build_textures_atlas()`?
"""
prompt.distractors = [
    "It loads multiple textures at the same time.",
    "It creates textures from `Image` structs.",
    "It builds a background map that covers the screen."
]
answer.answer = "It builds a combined atlas texture with all the loaded textures."
context = """
It's much more efficient to draw from a combined texture atlas.
"""
id = "1dd8bd6f-f576-4c59-81e8-49790df8d9d7"
