[[questions]]
type = "ShortAnswer"
prompt.prompt = "Which function is used to draw a circle on the screen?"
answer.answer = "draw_circle"
context = "The function `draw_circle()` is part of the Macroquad `shapes` namespace."
id = "4fb79a6d-d116-4f5e-b39a-a70c758cd3cc"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Why is the function `is_key_pressed()` used instead of `is_key_down()`?
"""
prompt.distractors = [
    "The function `is_key_down()` checks if the down arrow key is pressed.",
    "The function `is_key_pressed()` must be used for all keys that aren't letters."
]
answer.answer = "To ensure that only a single bullet is fired each time the key is pressed."
context = """
"""
id = "eb00283a-bc44-47e2-b007-576688ea71b4"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
What is the enu variant representing the space bar called?
"""
prompt.distractors = [
    "`Key::Space`",
    "`KeyCode::Spacebar`",
    "`Code::Space`"
]
answer.answer = "`KeyCode::Space`"
context = """
The `KeyCode` enum contains variants for all the keys on the keyboard.
"""
id = "9886a40f-82ff-48b7-bee6-c3faae518736"
