[[questions]]
type = "MultipleChoice"
prompt.prompt = """
In what time unit is the time returned from the function `get_frame_time`?
"""
prompt.distractors = [
  "nanoseconds",
  "microseconds",
  "milliseconds",
  "picoseconds"
]
answer.answer = "seconds"
context = """
The funtion `get_frame_time()` returns the time in seconds as a `f32`.
"""
id = "28533e84-c0df-41e7-9b6f-34415e56e985"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which function is used to get the time that has passed since the last frame?
"""
prompt.distractors = [
  "`get_delta_time()`",
  "`get_time()`",
  "`get_fps()`"
]
answer.answer = "`get_frame_time()`"
context = """
The function `get_frame_time()` returns the delta time since the last frame,
while `get_time()` returns the accumulated time since the application was started.
"""
id = "75a5919d-3c53-429f-b887-585791c62fa2"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Why is the `delta_time` value multiplied by `MOVEMENT_SPEED`?
"""
prompt.distractors = [
    "To increase the speed every frame.",
    "The time since the program was started defines how far the circle can move.",
    "To compensate when the computer clock is incorrect."
]
answer.answer = "So that the movement per second will always be the same."
context = """
The number of frames drawn per second may be different on different computers and platforms.
"""
id = "ee3f9956-9831-4b57-8c11-3876a77b46b6"
