[[questions]]
type = "ShortAnswer"
prompt.prompt = """
Which Macroquad function is used to set which `Material` to use?
"""
answer.answer = "gl_use_material"
context = """
The functions `gl_use_material()` and `gl_use_default_material()` are used to start and stop using a shader.
"""
id = "56f078b9-12bb-45df-8595-ea5b9dfc66c0"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which uniform is **NOT** available automatically in Macroquad shaders?
"""
prompt.distractors = [
  "`_Time`",
  "`Model`",
  "`Projection`",
  "`Texture`",
  "`_ScreenTexture`"
]
answer.answer = "`iResolution`"
context = """
The screen resolution isn't automatically added to the shaders
and has to be added manually to be used.
"""
id = "423ffde3-f8fe-450d-84ee-4bab080d4d4e"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
How do you set the value of a uniform?
"""
prompt.distractors = [
    "`gl_set_uniform(\"foo\", 1)`",
    "`material.set_params(\"foo\", 1)`",
    "`set_uniform(\"foo\".to_owned(), UniformType::Int1)`",
    "`gl_use_material(material, vec![\"foo\", 1])`"
]
answer.answer = "`material.set_uniform(\"foo\", 1)`"
context = """
The `Material` struct has the method `set_uniform()` which is
used to set uniform values on shaders.
"""
id = "e3c43a3f-9788-4422-8806-917d0015c68d"
